"""Insert Reset & Initialization requirements into DB."""
import sqlite3
import datetime

now = datetime.datetime.now(datetime.UTC).isoformat()
c = sqlite3.connect("nvme_req.db")

reqs = [
    # === Controller Reset (CC.EN) ===
    {
        "id": "REQ-RESET-CR-001",
        "level1": "RST Reset",
        "level2": "Controller Reset",
        "derived_from": "NVMe 2.2 §3.7.2",
        "spec_section": "§3.7.2",
        "spec_text": "When the host clears CC.EN from '1' to '0', the controller shall perform a Controller Reset: delete all I/O Submission Queues and I/O Completion Queues, reset the Admin Submission Queue and the Admin Completion Queue, and bring the hardware to an idle state.",
        "spec_text_ko": "호스트가 CC.EN을 '1'에서 '0'으로 클리어하면, 컨트롤러는 Controller Reset을 수행해야 한다: 모든 I/O Submission Queue 및 I/O Completion Queue를 삭제하고, Admin Submission Queue와 Admin Completion Queue를 리셋하며, 하드웨어를 유휴 상태로 전환해야 한다.",
        "keyword": "CC.EN Controller Reset delete queue idle",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-CR-002",
        "level1": "RST Reset",
        "level2": "Controller Reset",
        "derived_from": "NVMe 2.2 §3.7.2",
        "spec_section": "§3.7.2",
        "spec_text": "A Controller Reset shall not affect transport specific state (e.g., PCI Express registers including MMIO MSI-X registers), nor the Admin Queue properties (AQA, ASQ, or ACQ).",
        "spec_text_ko": "Controller Reset은 전송 계층 고유 상태(예: MMIO MSI-X 레지스터를 포함한 PCI Express 레지스터)와 Admin Queue 속성(AQA, ASQ, ACQ)에 영향을 미쳐서는 안 된다.",
        "keyword": "Controller Reset preserve AQA ASQ ACQ transport",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-CR-003",
        "level1": "RST Reset",
        "level2": "Controller Reset",
        "derived_from": "NVMe 2.2 §3.7.2",
        "spec_section": "§3.7.2",
        "spec_text": "The controller shall ensure that there is no impact (e.g., data loss) caused by a Controller Reset to the results of commands that have had corresponding completion queue entries posted to an I/O Completion Queue prior to that Controller Reset.",
        "spec_text_ko": "컨트롤러는 Controller Reset 이전에 I/O Completion Queue에 CQE가 포스팅된 명령의 결과에 대해 Controller Reset으로 인한 영향(예: 데이터 손실)이 없음을 보장해야 한다.",
        "keyword": "Controller Reset no data loss completed commands",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-CR-004",
        "level1": "RST Reset",
        "level2": "Controller Reset",
        "derived_from": "NVMe 2.2 §3.7.2",
        "spec_section": "§3.7.2",
        "spec_text": "Internal controller state (e.g., Feature values defined in section 5.1.25 that are not persistent across power states) shall be reset to their default values upon Controller Reset.",
        "spec_text_ko": "내부 컨트롤러 상태(예: 전원 상태 간 유지되지 않는 섹션 5.1.25에 정의된 Feature 값)는 Controller Reset 시 기본값으로 리셋되어야 한다.",
        "keyword": "Controller Reset default Feature values internal state",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-CR-005",
        "level1": "RST Reset",
        "level2": "Controller Reset",
        "derived_from": "NVMe 2.2 §3.7.2",
        "spec_section": "§3.7.2",
        "spec_text": "The Persistent Memory Region properties (PMRCAP, PMRCTL, PMRSTS, PMREBS, PMRSWTP, PMRMSCL, PMRMSCU) shall not be reset by Controller Reset.",
        "spec_text_ko": "Persistent Memory Region 속성(PMRCAP, PMRCTL, PMRSTS, PMREBS, PMRSWTP, PMRMSCL, PMRMSCU)은 Controller Reset에 의해 리셋되어서는 안 된다.",
        "keyword": "Controller Reset PMR preserve PMRCAP PMRCTL",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-CR-006",
        "level1": "RST Reset",
        "level2": "Controller Reset",
        "derived_from": "NVMe 2.2 §3.1.4",
        "spec_section": "§3.1.4",
        "spec_text": "CSTS.RDY shall be cleared to '0' when CC.EN is cleared to '0' once the controller is ready to be re-enabled.",
        "spec_text_ko": "컨트롤러가 재활성화 준비가 완료되면 CC.EN이 '0'으로 클리어될 때 CSTS.RDY를 '0'으로 클리어해야 한다.",
        "keyword": "CSTS.RDY clear CC.EN Controller Reset ready",
        "controller_type": "BOTH",
        "mandatory": "M",
    },

    # === NVM Subsystem Reset (NSSR) ===
    {
        "id": "REQ-RESET-NSSR-001",
        "level1": "RST Reset",
        "level2": "NVM Subsystem Reset",
        "derived_from": "NVMe 2.2 §3.7.3",
        "spec_section": "§3.7.3",
        "spec_text": "A write of the value 4E564D65h ('NVMe') to the NSSR.NSSRC field shall initiate an NVM Subsystem Reset. A write of any other value shall have no functional effect on the operation of the NVM subsystem.",
        "spec_text_ko": "NSSR.NSSRC 필드에 4E564D65h('NVMe') 값을 쓰면 NVM Subsystem Reset이 시작되어야 한다. 다른 값을 쓰면 NVM 서브시스템 동작에 기능적 영향이 없어야 한다.",
        "keyword": "NSSR NSSRC 4E564D65h NVMe write",
        "controller_type": "BOTH",
        "mandatory": "O",
    },
    {
        "id": "REQ-RESET-NSSR-002",
        "level1": "RST Reset",
        "level2": "NVM Subsystem Reset",
        "derived_from": "NVMe 2.2 §3.7.3",
        "spec_section": "§3.7.3",
        "spec_text": "The NSSR.NSSRC field shall return the value 0h when read.",
        "spec_text_ko": "NSSR.NSSRC 필드는 읽기 시 0h 값을 반환해야 한다.",
        "keyword": "NSSR NSSRC read 0h",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-NSSR-003",
        "level1": "RST Reset",
        "level2": "NVM Subsystem Reset",
        "derived_from": "NVMe 2.2 §3.7.3",
        "spec_section": "§3.7.3",
        "spec_text": "When an NVM Subsystem Reset occurs, the entire NVM subsystem shall be reset. This includes the initiation of a Controller Level Reset on all controllers that make up the NVM subsystem, disabling of the Persistent Memory Region associated with all controllers, and any transport specific actions.",
        "spec_text_ko": "NVM Subsystem Reset 발생 시, 전체 NVM 서브시스템이 리셋되어야 한다. 이는 NVM 서브시스템을 구성하는 모든 컨트롤러에 대한 Controller Level Reset 시작, 모든 컨트롤러와 연관된 Persistent Memory Region 비활성화, 전송 계층 고유 동작을 포함한다.",
        "keyword": "NVM Subsystem Reset all controllers CLR PMR disable",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-NSSR-004",
        "level1": "RST Reset",
        "level2": "NVM Subsystem Reset",
        "derived_from": "NVMe 2.2 §3.7.3",
        "spec_section": "§3.7.3",
        "spec_text": "The ability for host software to initiate an NVM Subsystem Reset by writing to the NSSR.NSSRC field is an optional capability indicated by the state of the CAP.NSSRS field.",
        "spec_text_ko": "호스트 소프트웨어가 NSSR.NSSRC 필드에 쓰기로 NVM Subsystem Reset을 시작하는 기능은 CAP.NSSRS 필드 상태로 표시되는 선택적 기능이다.",
        "keyword": "CAP.NSSRS optional NVM Subsystem Reset",
        "controller_type": "BOTH",
        "mandatory": "O",
    },
    {
        "id": "REQ-RESET-NSSR-005",
        "level1": "RST Reset",
        "level2": "NVM Subsystem Reset",
        "derived_from": "NVMe 2.2 §3.1.4",
        "spec_section": "§3.1.4",
        "spec_text": "An NVM Subsystem Reset shall clear the CSTS.ST bit to '0'. All other Controller Level Resets shall not change the value of this bit.",
        "spec_text_ko": "NVM Subsystem Reset은 CSTS.ST 비트를 '0'으로 클리어해야 한다. 다른 모든 Controller Level Reset은 이 비트 값을 변경해서는 안 된다.",
        "keyword": "NSSR CSTS.ST clear NVM Subsystem Reset",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-NSSR-006",
        "level1": "RST Reset",
        "level2": "NVM Subsystem Reset",
        "derived_from": "NVMe 2.2 §3.1.4",
        "spec_section": "§3.1.4",
        "spec_text": "If an NVM Subsystem Shutdown is reported as in progress or complete (CSTS.ST set to '1' and CSTS.SHST set to 01b or 10b), then an NVM Subsystem Reset is required before CSTS.RDY is allowed to be set to '1' from '0'.",
        "spec_text_ko": "NVM Subsystem Shutdown이 진행 중이거나 완료됨으로 보고된 경우(CSTS.ST가 '1'이고 CSTS.SHST가 01b 또는 10b), CSTS.RDY를 '0'에서 '1'로 설정하기 전에 NVM Subsystem Reset이 필요하다.",
        "keyword": "NVM Subsystem Shutdown CSTS.RDY NSSR required",
        "controller_type": "BOTH",
        "mandatory": "M",
    },

    # === Controller Level Reset (공통) ===
    {
        "id": "REQ-RESET-CLR-001",
        "level1": "RST Reset",
        "level2": "Controller Level Reset",
        "derived_from": "NVMe 2.2 §3.7.2",
        "spec_section": "§3.7.2",
        "spec_text": "A Controller Level Reset shall consist of: stopping processing of any outstanding Admin or I/O commands, deleting all I/O Submission and Completion Queues, bringing the controller to an idle state (CSTS.RDY cleared to '0'), and resetting all NVMe controller properties and internal state with specified exceptions.",
        "spec_text_ko": "Controller Level Reset은 다음으로 구성되어야 한다: 미처리 Admin 또는 I/O 명령 처리 중단, 모든 I/O Submission 및 Completion Queue 삭제, 컨트롤러를 유휴 상태로 전환(CSTS.RDY를 '0'으로 클리어), 지정된 예외를 제외한 모든 NVMe 컨트롤러 속성 및 내부 상태 리셋.",
        "keyword": "Controller Level Reset stop commands delete queues idle",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-CLR-002",
        "level1": "RST Reset",
        "level2": "Controller Level Reset",
        "derived_from": "NVMe 2.2 §3.7.2",
        "spec_section": "§3.7.2",
        "spec_text": "A Controller Level Reset is initiated by: NVM Subsystem Reset, Controller Reset (host clears CC.EN from '1' to '0'), or transport specific reset types defined in the applicable NVMe Transport binding specification.",
        "spec_text_ko": "Controller Level Reset은 NVM Subsystem Reset, Controller Reset(호스트가 CC.EN을 '1'에서 '0'으로 클리어), 또는 해당 NVMe Transport 바인딩 사양에 정의된 전송 계층 고유 리셋 유형으로 시작된다.",
        "keyword": "CLR initiation NSSR Controller Reset transport",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-CLR-003",
        "level1": "RST Reset",
        "level2": "Controller Level Reset",
        "derived_from": "NVMe 2.2 §3.7.2",
        "spec_section": "§3.7.2",
        "spec_text": "In all Controller Level Reset cases except a Controller Reset, the controller properties defined by the transport (e.g., the PCIe registers defined by the PCIe Base Specification) shall be reset as defined by the applicable NVMe Transport binding specification.",
        "spec_text_ko": "Controller Reset을 제외한 모든 Controller Level Reset 경우에, 전송 계층이 정의한 컨트롤러 속성(예: PCIe Base Specification이 정의한 PCIe 레지스터)은 해당 NVMe Transport 바인딩 사양에 따라 리셋되어야 한다.",
        "keyword": "CLR transport properties PCIe reset except Controller Reset",
        "controller_type": "BOTH",
        "mandatory": "M",
    },

    # === CSTS.SHST와 Reset 상호작용 ===
    {
        "id": "REQ-RESET-CLR-004",
        "level1": "RST Reset",
        "level2": "Controller Level Reset",
        "derived_from": "NVMe 2.2 §3.1.4",
        "spec_section": "§3.1.4",
        "spec_text": "If CSTS.SHST is set to 01b (shutdown processing in progress) when a CLR is initiated, an NVM Subsystem Reset shall abort both a controller shutdown and an NVM Subsystem Shutdown. Any other type of CLR shall not abort an NVM Subsystem Shutdown.",
        "spec_text_ko": "CLR 시작 시 CSTS.SHST가 01b(종료 처리 진행 중)로 설정된 경우, NVM Subsystem Reset은 컨트롤러 종료와 NVM Subsystem Shutdown을 모두 중단해야 한다. 다른 유형의 CLR은 NVM Subsystem Shutdown을 중단해서는 안 된다.",
        "keyword": "CSTS.SHST CLR shutdown abort NVM Subsystem Reset",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-CLR-005",
        "level1": "RST Reset",
        "level2": "Controller Level Reset",
        "derived_from": "NVMe 2.2 §3.1.4",
        "spec_section": "§3.1.4",
        "spec_text": "If CSTS.SHST is cleared to 00b (normal operation) when a CLR is initiated, then that CLR shall not change the value of this field. If CSTS.SHST is set to 10b (shutdown complete) and the CLR is initiated by NVM Subsystem Reset, then that CLR shall clear this field to 00b.",
        "spec_text_ko": "CLR 시작 시 CSTS.SHST가 00b(정상 동작)로 클리어된 경우, 해당 CLR은 이 필드 값을 변경해서는 안 된다. CSTS.SHST가 10b(종료 완료)이고 CLR이 NVM Subsystem Reset으로 시작된 경우, 해당 CLR은 이 필드를 00b로 클리어해야 한다.",
        "keyword": "CSTS.SHST CLR normal operation shutdown complete",
        "controller_type": "BOTH",
        "mandatory": "M",
    },

    # === Function Level Reset ===
    {
        "id": "REQ-RESET-FLR-001",
        "level1": "RST Reset",
        "level2": "Function Level Reset",
        "derived_from": "NVMe 2.2 §3.7.2",
        "spec_section": "§3.7.2",
        "spec_text": "A Function Level Reset shall initiate a Controller Level Reset. The Controller Memory Buffer Memory Space Control property (CMBMSC) shall not be reset as part of a Controller Level Reset caused by a Function Level Reset.",
        "spec_text_ko": "Function Level Reset은 Controller Level Reset을 시작해야 한다. Function Level Reset으로 인한 Controller Level Reset의 일부로 CMBMSC(Controller Memory Buffer Memory Space Control) 속성은 리셋되어서는 안 된다.",
        "keyword": "FLR Function Level Reset CMBMSC preserve",
        "controller_type": "BOTH",
        "mandatory": "M",
    },

    # === CC.EN Enable 전환 (초기화 전제조건) ===
    {
        "id": "REQ-RESET-EN-001",
        "level1": "RST Reset",
        "level2": "Controller Enable",
        "derived_from": "NVMe 2.2 §3.1.4",
        "spec_section": "§3.1.4",
        "spec_text": "Host software shall set CC.AMS, CC.MPS, and CC.CSS to valid values prior to enabling the controller by setting CC.EN to '1'.",
        "spec_text_ko": "호스트 소프트웨어는 CC.EN을 '1'로 설정하여 컨트롤러를 활성화하기 전에 CC.AMS, CC.MPS, CC.CSS를 유효한 값으로 설정해야 한다.",
        "keyword": "CC.EN enable CC.AMS CC.MPS CC.CSS prerequisite",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-RESET-EN-002",
        "level1": "RST Reset",
        "level2": "Controller Enable",
        "derived_from": "NVMe 2.2 §3.1.4",
        "spec_section": "§3.1.4",
        "spec_text": "If a controller shutdown is reported as in progress or complete (CSTS.ST cleared to '0' and CSTS.SHST set to 01b or 10b), then before CSTS.RDY is allowed to be set to '1', controller shutdown processing shall stop and the CSTS.SHST field shall be cleared to 00b.",
        "spec_text_ko": "컨트롤러 종료가 진행 중이거나 완료된 것으로 보고된 경우(CSTS.ST가 '0'이고 CSTS.SHST가 01b 또는 10b), CSTS.RDY를 '1'로 설정하기 전에 컨트롤러 종료 처리가 중단되어야 하고 CSTS.SHST 필드가 00b로 클리어되어야 한다.",
        "keyword": "CSTS.RDY enable shutdown CSTS.SHST clear",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
]

for r in reqs:
    r.setdefault("category", "RESET")
    c.execute(
        """INSERT OR IGNORE INTO requirement
        (id, category, level1, level2, derived_from, spec_section, spec_text, spec_text_ko,
         keyword, controller_type, mandatory, support_status, status, priority, created_at, updated_at)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
        (
            r["id"], r["category"], r["level1"], r["level2"], r["derived_from"], r["spec_section"],
            r["spec_text"], r["spec_text_ko"], r["keyword"], r["controller_type"], r["mandatory"],
            "UNKNOWN", "OPEN", "NORMAL", now, now,
        ),
    )
    print(f"  ADD: {r['id']}")

c.commit()
c.close()
print(f"\nImported {len(reqs)} Reset requirements.")
