"""Insert Firmware Download / Commit / Slot Info requirements into DB."""
import sqlite3
import datetime

now = datetime.datetime.utcnow().isoformat()
c = sqlite3.connect("nvme_req.db")

reqs = [
    # --- Firmware Image Download (§5.1.9) ---
    {
        "id": "REQ-FW-DL-001",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.9",
        "spec_section": "§5.1.9",
        "spec_text": "The controller shall support the Firmware Image Download command (Opcode 11h) to download all or a portion of a firmware image for a future update to the controller.",
        "spec_text_ko": "컨트롤러는 향후 컨트롤러 업데이트를 위해 펌웨어 이미지 전체 또는 일부를 다운로드하는 Firmware Image Download 명령(Opcode 11h)을 지원해야 한다.",
        "keyword": "Firmware Image Download 11h",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-DL-002",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.9",
        "spec_section": "§5.1.9",
        "spec_text": "The Firmware Image Download command shall use the Command Dword 10 (NUMD) field to specify the number of dwords to transfer and Command Dword 11 (OFST) field to specify the dword offset from the start of the firmware image.",
        "spec_text_ko": "Firmware Image Download 명령은 Command Dword 10(NUMD) 필드로 전송할 dword 수를, Command Dword 11(OFST) 필드로 펌웨어 이미지 시작 지점으로부터의 dword 오프셋을 지정해야 한다.",
        "keyword": "CDW10 NUMD CDW11 OFST",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-DL-003",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.9",
        "spec_section": "§5.1.9",
        "spec_text": "If the NUMD field or OFST field value does not meet the requirement indicated by the FWUG field in the Identify Controller data structure, then the controller may abort the command with a status code of Invalid Field in Command.",
        "spec_text_ko": "NUMD 또는 OFST 필드 값이 Identify Controller 데이터 구조의 FWUG 필드에 명시된 요구사항을 충족하지 않는 경우, 컨트롤러는 Invalid Field in Command 상태 코드로 명령을 중단할 수 있다.",
        "keyword": "FWUG alignment granularity Invalid Field",
        "controller_type": "BOTH",
        "mandatory": "O",
    },
    {
        "id": "REQ-FW-DL-004",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.9",
        "spec_section": "§5.1.9",
        "spec_text": "Processing of the first Firmware Image Download command after completion of a Firmware Commit command shall cause the controller to discard all remaining portion(s), if any, of downloaded images.",
        "spec_text_ko": "Firmware Commit 명령 완료 후 첫 번째 Firmware Image Download 명령 처리 시, 컨트롤러는 다운로드된 이미지의 남은 부분(있는 경우)을 모두 폐기해야 한다.",
        "keyword": "discard downloaded image after Firmware Commit",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-DL-005",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.9",
        "spec_section": "§5.1.9",
        "spec_text": "If a Controller Level Reset occurs between a firmware download and completion of the Firmware Commit command, then the controller shall discard all portion(s), if any, of downloaded images.",
        "spec_text_ko": "펌웨어 다운로드와 Firmware Commit 명령 완료 사이에 Controller Level Reset이 발생하면, 컨트롤러는 다운로드된 이미지의 모든 부분(있는 경우)을 폐기해야 한다.",
        "keyword": "Controller Level Reset discard downloaded image",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-DL-006",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.9",
        "spec_section": "§5.1.9",
        "spec_text": "If the controller detects that the firmware image has overlapping ranges, it may return an error of Overlapping Range (status value 14h).",
        "spec_text_ko": "컨트롤러가 펌웨어 이미지에 중복 범위가 있음을 감지하면, Overlapping Range(상태 값 14h) 오류를 반환할 수 있다.",
        "keyword": "Overlapping Range 14h firmware download",
        "controller_type": "BOTH",
        "mandatory": "O",
    },
    {
        "id": "REQ-FW-DL-007",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.9",
        "spec_section": "§5.1.9",
        "spec_text": "Upon completion of the Firmware Image Download command, the controller shall post a completion queue entry to the Admin Completion Queue.",
        "spec_text_ko": "Firmware Image Download 명령 완료 시, 컨트롤러는 Admin Completion Queue에 CQE를 포스팅해야 한다.",
        "keyword": "Firmware Image Download CQE completion",
        "controller_type": "BOTH",
        "mandatory": "M",
    },

    # --- Firmware Commit (§5.1.8) ---
    {
        "id": "REQ-FW-CMT-001",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.8",
        "spec_section": "§5.1.8",
        "spec_text": "The controller shall support the Firmware Commit command (Opcode 10h) to verify that a valid firmware image has been downloaded and commit that revision to a specific firmware slot.",
        "spec_text_ko": "컨트롤러는 유효한 펌웨어 이미지가 다운로드되었는지 확인하고 해당 리비전을 특정 펌웨어 슬롯에 커밋하는 Firmware Commit 명령(Opcode 10h)을 지원해야 한다.",
        "keyword": "Firmware Commit 10h firmware slot",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-CMT-002",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.8",
        "spec_section": "§5.1.8",
        "spec_text": "The Firmware Commit command shall use the Command Dword 10 field containing the Commit Action (CA) in bits 05:03 and the Firmware Slot (FS) in bits 02:00.",
        "spec_text_ko": "Firmware Commit 명령은 Command Dword 10 필드를 사용하며, 비트 05:03에 Commit Action(CA), 비트 02:00에 Firmware Slot(FS)을 포함해야 한다.",
        "keyword": "CDW10 Commit Action CA Firmware Slot FS",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-CMT-003",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.8",
        "spec_section": "§5.1.8",
        "spec_text": "If the Firmware Slot (FS) field is set to 0h, then the controller shall choose the firmware slot (i.e., slot 1 to slot 7) to use for the operation.",
        "spec_text_ko": "Firmware Slot(FS) 필드가 0h로 설정된 경우, 컨트롤러는 작업에 사용할 펌웨어 슬롯(슬롯 1~7)을 선택해야 한다.",
        "keyword": "FS 0h controller choose firmware slot",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-CMT-004",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.8",
        "spec_section": "§5.1.8",
        "spec_text": "For Firmware Commit commands with CA set to 001b or 010b that complete with status code 0h (Success), a Controller Level Reset initiated by any of the methods defined in section 3.7.2 shall activate the specified firmware.",
        "spec_text_ko": "CA가 001b 또는 010b로 설정되고 상태 코드 0h(성공)으로 완료된 Firmware Commit 명령에 대해, 섹션 3.7.2에 정의된 방법으로 시작된 Controller Level Reset은 지정된 펌웨어를 활성화해야 한다.",
        "keyword": "CA 001b 010b Controller Level Reset activate firmware",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-CMT-005",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.8",
        "spec_section": "§5.1.8",
        "spec_text": "If the Commit Action field is set to 011b and activation results in a change in controller behavior that is not expected by the host (e.g., an incompatible change), then the controller shall abort the command with a status code of Firmware Activation Requires Conventional Reset.",
        "spec_text_ko": "Commit Action 필드가 011b로 설정되고 활성화가 호스트가 예상하지 않는 컨트롤러 동작 변경(예: 호환되지 않는 변경)을 초래하는 경우, 컨트롤러는 Firmware Activation Requires Conventional Reset 상태 코드로 명령을 중단해야 한다.",
        "keyword": "CA 011b incompatible Firmware Activation Requires Conventional Reset",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-CMT-006",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.8",
        "spec_section": "§5.1.8",
        "spec_text": "Upon completion of the Firmware Commit command, the controller shall post a completion queue entry to the Admin Completion Queue indicating the status for the command.",
        "spec_text_ko": "Firmware Commit 명령 완료 시, 컨트롤러는 Admin Completion Queue에 명령의 상태를 나타내는 CQE를 포스팅해야 한다.",
        "keyword": "Firmware Commit CQE Admin Completion Queue",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-CMT-007",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.8",
        "spec_section": "§5.1.8",
        "spec_text": "The controller shall return Invalid Firmware Slot (status value 06h) if the firmware slot indicated is invalid or read only, or if the firmware slot exceeds the number supported.",
        "spec_text_ko": "지정된 펌웨어 슬롯이 유효하지 않거나 읽기 전용이거나, 지원 수를 초과하는 경우 컨트롤러는 Invalid Firmware Slot(상태 값 06h)을 반환해야 한다.",
        "keyword": "Invalid Firmware Slot 06h",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-CMT-008",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.8",
        "spec_section": "§5.1.8",
        "spec_text": "The controller shall return Invalid Firmware Image (status value 07h) if the firmware image specified for activation is invalid and not loaded by the controller, or if the specified firmware slot does not contain a firmware image.",
        "spec_text_ko": "활성화를 위해 지정된 펌웨어 이미지가 유효하지 않아 컨트롤러에 의해 로드되지 않았거나, 지정된 펌웨어 슬롯에 펌웨어 이미지가 없는 경우 Invalid Firmware Image(상태 값 07h)를 반환해야 한다.",
        "keyword": "Invalid Firmware Image 07h",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-CMT-009",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.8",
        "spec_section": "§5.1.8",
        "spec_text": "If CA is set to 011b and activation requires more time than MTFA, the controller shall return Firmware Activation Requires Maximum Time Violation (status value 12h) and the firmware image shall not be activated.",
        "spec_text_ko": "CA가 011b로 설정되고 활성화에 MTFA보다 더 많은 시간이 필요한 경우, 컨트롤러는 Firmware Activation Requires Maximum Time Violation(상태 값 12h)을 반환해야 하며, 펌웨어 이미지는 활성화되지 않아야 한다.",
        "keyword": "MTFA Maximum Time Violation 12h",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-CMT-010",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.8",
        "spec_section": "§5.1.8",
        "spec_text": "If the controller detects overlapping firmware/boot partition image update command sequences, the results shall be reported in Dword 0 of the completion queue entry with the Multiple Update Detected (MUD) field.",
        "spec_text_ko": "컨트롤러가 중복 펌웨어/부트 파티션 이미지 업데이트 명령 시퀀스를 감지한 경우, CQE의 Dword 0에 Multiple Update Detected(MUD) 필드로 결과를 보고해야 한다.",
        "keyword": "MUD Multiple Update Detected overlapping",
        "controller_type": "BOTH",
        "mandatory": "M",
    },

    # --- Firmware Slot Information Log Page (§5.1.12.1.4) ---
    {
        "id": "REQ-FW-SLOT-001",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.12.1.4",
        "spec_section": "§5.1.12.1.4",
        "spec_text": "The controller shall support the Firmware Slot Information log page (LID 03h) to describe the firmware revision stored in each firmware slot supported and indicate the active slot number.",
        "spec_text_ko": "컨트롤러는 지원하는 각 펌웨어 슬롯에 저장된 펌웨어 리비전을 설명하고 활성 슬롯 번호를 나타내는 Firmware Slot Information 로그 페이지(LID 03h)를 지원해야 한다.",
        "keyword": "Firmware Slot Information LID 03h",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-SLOT-002",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.12.1.4",
        "spec_section": "§5.1.12.1.4",
        "spec_text": "The Firmware Slot Information log page shall contain the Active Firmware Info (AFI) byte with the Current Active Firmware Slot (CAFS) field in bits 2:0 indicating the firmware slot from which the actively running firmware revision was loaded.",
        "spec_text_ko": "Firmware Slot Information 로그 페이지는 Active Firmware Info(AFI) 바이트를 포함해야 하며, 비트 2:0의 Current Active Firmware Slot(CAFS) 필드로 현재 실행 중인 펌웨어 리비전이 로드된 펌웨어 슬롯을 나타내야 한다.",
        "keyword": "AFI CAFS Current Active Firmware Slot",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-SLOT-003",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.12.1.4",
        "spec_section": "§5.1.12.1.4",
        "spec_text": "The AFI byte shall contain the Next Active Firmware Slot (NAFS) field in bits 6:4 indicating the firmware slot that is going to be activated at the next Controller Level Reset. If cleared to 0h, the controller does not indicate the firmware slot to be activated at the next Controller Level Reset.",
        "spec_text_ko": "AFI 바이트는 비트 6:4의 Next Active Firmware Slot(NAFS) 필드를 포함해야 하며, 다음 Controller Level Reset에서 활성화될 펌웨어 슬롯을 나타낸다. 0h로 클리어된 경우 다음 Controller Level Reset에서 활성화될 펌웨어 슬롯을 나타내지 않는다.",
        "keyword": "NAFS Next Active Firmware Slot",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
    {
        "id": "REQ-FW-SLOT-004",
        "category": "FW_MGMT",
        "level1": "FW Firmware Update Process",
        "level2": "FW Download",
        "derived_from": "NVMe 2.2 §5.1.12.1.4",
        "spec_section": "§5.1.12.1.4",
        "spec_text": "The Firmware Slot Information log page shall contain the Firmware Revision for Slot 1 through Slot 7 (FRS1-FRS7) fields as 8-byte ASCII strings. If no valid firmware revision is present or if the slot is unsupported, the field shall be cleared to 0h.",
        "spec_text_ko": "Firmware Slot Information 로그 페이지는 슬롯 1~7의 Firmware Revision(FRS1-FRS7) 필드를 8바이트 ASCII 문자열로 포함해야 한다. 유효한 펌웨어 리비전이 없거나 슬롯이 지원되지 않는 경우, 해당 필드는 0h로 클리어되어야 한다.",
        "keyword": "FRS1 FRS7 Firmware Revision ASCII slot",
        "controller_type": "BOTH",
        "mandatory": "M",
    },
]

for r in reqs:
    c.execute(
        """INSERT OR IGNORE INTO requirement
        (id, category, level1, level2, derived_from, spec_section, spec_text, spec_text_ko,
         keyword, controller_type, mandatory, support_status, status, priority, created_at, updated_at)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
        (
            r["id"], r["category"], r["level1"], r["level2"], r["derived_from"], r["spec_section"],
            r["spec_text"], r["spec_text_ko"], r["keyword"], r["controller_type"], r["mandatory"],
            "UNKNOWN", "OPEN", "NORMAL", now, now,
        ),
    )
    print(f"  ADD: {r['id']}")

c.commit()
c.close()
print(f"\nImported {len(reqs)} Firmware requirements.")
